### PR TITLE
First version of polish translation.

### PR DESCRIPTION
**Pull request by AreYouLoco**
I added some comments and ideas in comments inside file.
I have been trying to translate in a way so it doesn't sound weird in polish.

Greetings

### CODE REVIEW

**Comment by wish7code** [comment]
Thanks a lot!

**Comment by AreYouLoco** [comment]
Cool, no problem.

Please update app on f-droid because your github source has some new stuff. So I can test it. Or teach me how to build properly and maybe I will update it to be 100% sure with this translation.

**Comment by wish7code** [comment]
If one or two weaks is ok for you, wait for the next f-droid release. I'm still testing #105..

In case you would like to build a local test version, it should compile in AndroidStudio right away (though big fat warning: you would loose your local wifi and cell database in such case, as your local AndroidStudio signature differs from the f-droid signature!!)
 
Let me know if this helps..

**Comment by AreYouLoco** [comment]
Yeah I think I will manage I have only sdk installed I will install AStudio then. Anyway I wanted to do it to compile some other stuff.

So I will try to do it and test out.

**Pull request merged**
