### PR TITLE
Update SsidBlackListBootstraper.java

### PR DESCRIPTION
**Pull request by amilopowers**
I added some Swiss Wifi networks which are in busses and therefor mobile.

### CODE REVIEW

**Comment by wish7code** [comment]
Merged :-)

**Comment by agilob** [comment]
No, you need to add upstream link to this repo in your local repository, it's something like `git remote add upstream git@github.com:wish7code/openbmap.git`

When you make new PR, do:
```
git checkout upstream master
git pull upstream master
git checkout -b new_branch_unique_name
``` start working on that branch and committing there.

**Comment by amilopowers** [comment]
"Local repo" meaning that I need some kind of desktop client?

**Comment by wish7code** [comment]
Local repo is basically the place where your store your local code version. With the commands agilob suggested, you'll overwrite your local version with more recent server updates. In other words, you'll apply the latest server updates to your local copy.

To edit the files you'll just need a text editor, to manage above mentioned updates and pull request you'll typically need a git client (if you're on windows have a look e.g. at https://tortoisegit.org/)

**Comment by amilopowers** [comment]
Thank you! I bet there's something for Fedora Linux.

**Comment by agilob** [comment]
Try git-kraken, it's good and if you don't know command line it will make everything easier.

**Comment by amilopowers** [comment]
Does someone of you know "gitg"? It is quite simple but I didn't get yet how to keep things in sync... And the commands @agilob suggested give me that:

```
[amilopowers@localhost ~]$ git checkout upstream master
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

```

**Comment by agilob** [comment]
@amilopowers you need to be in a git repository folder.

**Comment by amilopowers** [comment]
I still dont understand how those local repos work. I might check on that again but later.

**Comment by gdt** [comment]
Read this book, and things will be much clearer.  Trying to use git without really understanding it will not be a happy situation.   https://progit.org/

**Comment by agilob** [comment]
https://www.learnenough.com/git-tutorial try this instead of the book above, this is one is github-specific.

**Comment by amilopowers** [comment]
I will look into these two because I am really eager to learn all that coding and git. Thank you!

**Comment by amilopowers** [comment]
@agilob Since I read thru a part of the "Gitpro" book I tried the commands you proposed before.

> 
> git checkout upstream master
> git pull upstream master
> git checkout -b new_branch_unique_name

This is what I get:
```
[amilopowers@localhost openbmap]$ git status
Auf Branch master
Ihr Branch ist auf dem selben Stand wie 'origin/master'.
nichts zu committen, Arbeitsverzeichnis unverändert
[amilopowers@localhost openbmap]$ git checkout upstream master
error: pathspec 'upstream' did not match any file(s) known to git.
error: pathspec 'master' did not match any file(s) known to git.
[amilopowers@localhost openbmap]$ git pull upstream master
fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Can you help me again please?

**Comment by agilob** [comment]
Did you do `git remote add upstream git@github.com:wish7code/openbmap.git` as said above? I didn't recommend any book.

**Pull request merged**
